CREATE SEQUENCE unit_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE yard_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE employee_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE motorcycle_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE device_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE user_seq START WITH 1 INCREMENT BY 1;